[tool.robotpy]
robotpy_version = "2026.2.1.1"
components = [
  "apriltag",
  "commands2"
]
requires = [
  "robotpy-rev==2026.0.3.1",
  "robotpy-navx==2026.0.1.1",
  "robotpy-pathplannerlib==2026.1.2",
  "photonlibpy==2026.2.2"
]